allowBuilds:
  core-js: false
  esbuild: true
minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "@solidjs/*"
  - filesystem-routing
  - seroval
  - seroval-plugins
  - solid-js
updateNotifier: false
